
/**
 * Config file for WebSocketServer
 */
const config = {
    HOST: 'localhost',
    PORT: 5000,
    MAX_WATCHERS_COUNT: 20,
    MAX_PLAYERS_COUNT: 10,
    MAX_BOTS_COUNT: 9,
    SEND_INTERVAL: 50,
    RECEIVE_INTERVAL: 250,
    SIMULATE_INTERVAL: 50,
    MAX_NAME_LENGTH: 10,
    BOLIDE_SIZE: 2,
    ENGINE_ON_TTL: 7,
    VELOCITY_LIMIT: 8,
    WIDTH: 800,
    HEIGHT: 450,
    COLORS: [
        'red',
        'black',
        'blue',
        'green',
        'yellow',
        'purple',
        'maroon',
        'orange',
        'olive',
        'tan',
        'lime',
        'indigo',
        'purple',
        'gray',
        'navy',
        'khaki',
        'coral',
        'brown',
    ],
    BOT_NAMES: [
        'Jack',
        'Bill',
        'Bob',
        'Steel',
        'Kali',
        'Liam',
        'Mark',
        'Grok',
        'Ares',
        'Ilia',
        'Lord',
        'Wendy',
        'Racer',
        'Class',
        'Rand',
        'Piter',
    ],
}

module.exports = config;